GET http://localhost:8088/users

### GET request
GET http://localhost:8088/users/1

### POST
POST http://localhost:8088/users
Content-Type: application/json

{
  "name": "하이"
}

### DElETE
DELETE  http://localhost:8088/users/100

### GET
GET http://localhost:8088/hello-world-internationalized
Accept-Language: kr

### GET
GET http://localhost:8088/admin/users/1
Authentication-Info: DEV
#### GET
